<?php
    return [
        'documents_path_folder' => 'public/documents',
        'thumbnails_path_folder' => 'public/thumbnails',
        'null' => null,
        'true' => true,
        'number_per_page' => 10,
        'number_new_documents' => 3,
        'thumbnails' => 'thumbnails/',
        'avatar_path' => 'avatars/',
        'false' => 'false',
        'is_not_friend' => 0,
        'is_friend' => 1,
        'request_send' => 2,
        'request_receive' => 3,
        'documents_path' => 'documents/',
        'download_path' => 'public/documents/',
        'documents' => '/documents/',
        'download' => 1,
        'view' => 2,
        'zero' => 0,
        'viettel' => 1,
        'mobiphone' => 2,
        'vnd' => ' VND',
        'images_path' => 'images/home/',
    ];
?>
